config/routes.rb
Rails.application.routes.draw do
	mount Rswag::Ui::Engine => '/api-docs'
	mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
	devise_for :users
  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root to: 'users#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
   end
  # root "articles#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  #API routes
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes
  validates :name, presence: true # Name must not be blank.
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }
  after_initialize :set_defaults

  # Initialize the posts_counter to zero if it's nil.
  def set_defaults
    self.posts_counter ||= 0
  end

  # Method to return the 3 most recent posts for a given user.
  def recent_posts
    Post
      .where(author_id: id)
      .order(updated_at: :desc)
      .limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user_select = User.find(params[:id])
  end

  private

  def find_user
    @user = current_user
  end
end

app/views/users/_side_menu.html.erb
<div class="side-menu hide">
	<i class="fa-solid fa-x", style="font-size: 1.6em;", onclick="document.querySelector('.side-menu').style.display = 'none'"></i>
	<div class="flex-column">
		<div style="text-align: center;">
			<img class="users-photos", style="height: 100px;" src=<%= @user.photo %> />
			<p class="login-title", style="font-size: 1.3em;"><%= @user.name %></p>
		</div>
		<%= button_to destroy_user_session_path, method: :delete, class: 'button-posts' do %>
      Log Out
      <i class="fa-solid fa-right-from-bracket"></i>
    <% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="users-container">
	<%= render 'side_menu' %>
	<div style="width: 100%;">
		<i class="fa-solid fa-bars", style="font-size: 1.6em; position: fixed;", onclick="document.querySelector('.side-menu').style.display = 'block'"></i>
	</div>
	<% @users.each do |user| %>
		<div class="users">
			<img src="<%= user.photo %>" class="users-photos" />
			<div class="user-container">
				<%= link_to user_path(user.id), method: :get do %>
					<p class="users-name"><%= user.name %></p>
				<% end %>
				<p class="users-posts-counter">Number of posts: <%= user.posts_counter %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="users-container">
	<div id="posts-bar">
		<%= link_to users_path, method: :get, class: 'button-posts' do %>
    	<i class="fas fa-arrow-left"></i> Back to Users
  	<% end %>
  	<div id="edit-create-post">
			<% if can? :edit, @user_select %>
						<%= link_to edit_user_registration_path, method: :get, class: 'button-posts' do %>
							<i class="fa-solid fa-pen-to-square"></i>
							 Edit Info
						<% end %>
					<% end %>
					<% if can? :create, @user_select %>
						<%= link_to new_user_post_path(@user_select), method: :get, class: 'button-posts' do %>
							Create a new post
						<% end %>
					<% end %>
		</div>
  </div>
	<div class="users">
		<img src="<%= @user_select.photo %>" class="users-photos" />
		<div class="user-container">
			<p class="users-name"><%= @user_select.name %></p>
			<p class="users-posts-counter">Number of posts: <%= @user_select.posts_counter %></p>
		</div>
	</div>
	<div class="user-bio">
		<p>Bio:</p>
		<%= @user_select.bio %>
	</div>
	<div class="posts-container">
		<% @user_select.recent_posts.each do |post| %>
			<div class="posts">
				<%= link_to user_post_path(@user_select, post), method: :get do %>
        	<p><%= post.title %></p>
        <% end %>
				<p><%= post.text.truncate(50) %></p>
				<p>
					<span>Comments: <%= post.comments_counter %></span>
					<span>Likes: <%= post.likes_counter %>
					</span>
				</p>
			</div>
		<% end %>
	</div>
	<% unless @user_select.recent_posts.empty? %>
		<%= link_to user_posts_path(@user_select), method: :get, class: 'button-posts' do %>
			See all posts
		<% end %>
	<% end %>
</div>