config/routes.rb
Rails.application.routes.draw do
	mount Rswag::Ui::Engine => '/api-docs'
	mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
	devise_for :users
  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root to: 'users#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
   end
  # root "articles#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  #API routes
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User'
  after_initialize :set_defaults
  after_create :update_posts
  after_destroy :decrease_posts_counter
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }
  validates :likes_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  # Initialize counter to zero if they are nil.
  def set_defaults
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  # Method to update the posts_counter for a user.
  def update_posts
    user = User.find_by(id: author_id)
    user.increment!(:posts_counter)
  end

  def decrease_posts_counter
    user = User.find_by(id: author_id)
    user.decrement!(:posts_counter)
  end

  # Method to return the 5 most recent comments for a post.
  def recent_comments
    Comment
      .where(post_id: id)
      .includes(:user)
      .order(updated_at: :desc)
      .limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: params[:user_id])
    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user_select = User.find(params[:user_id])
    @posts = Post.where(author_id: params[:user_id])
    @user = current_user
  end

  def show
    @id = params[:id]
    @user_select = User.find(params[:user_id])
    @user = current_user
    @posts = Post.where(author_id: @user_select.id)
    @post = Post.find(@id)
    @like = Like.find_by(user: @user, post: @post)
    @next_post = Post.where('id > ? AND author_id = ?', params[:id], @user_select.id).first
    @previous_post = Post.where('id < ? AND author_id = ?', params[:id], @user_select.id).last
    @comments = Comment.where(post_id: @post.id).includes(:user)
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @user = current_user
    @post.author = @user

    if @post.save
      redirect_to user_posts_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
    @post = Post.find_by(author: @user, id: params[:id])
  end

  def update
    @user = current_user
    @post = Post.find_by(author: @user, id: params[:id])

    if @post.update(post_params)
      redirect_to user_posts_path(@user)
    else
      render :edit, status: unprocessable_entity
    end
  end

  def destroy
    @post = Post.find_by(author: params[:user_id], id: params[:id])

    @post.comments&.destroy_all
    @post.likes&.destroy_all
    @post&.destroy

    redirect_to request.referrer
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :author)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/views/posts/_form.html.erb
<%= bootstrap_form_with model: [@user, @post], class: 'posts-form' do |form| %>
	<%= form.text_field :title, class: 'posts-form-inputs' %>
	<%= form.text_area :text, size: "100x10", class: 'posts-form-inputs' %>
	<%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="users-container">
	<div id="posts-bar">
		<%= link_to :back, method: :get, class: 'button-posts' do %>
				<i class="fas fa-arrow-left"></i> Back to User
			<% end %>
		<h1>Edit Post</h1>
	</div>
	<%= render "form" %>
</div>

app/views/posts/index.html.erb
<div class="users-container">
	<div id="posts-bar">
		<%= link_to user_path(@user_select), method: :get, class: 'button-posts' do %>
			<i class="fas fa-arrow-left"></i> Back to User
		<% end %>
		<% if can? :create, @user_select %>
			<%= link_to new_user_post_path(@user_select), method: :get, class: 'button-posts' do %>
				Create a new post
			<% end %>
		<% end %>
  </div>
	<div class="users">
		<img src="<%= @user_select.photo %>" class="users-photos" />
		<div class="user-container">
			<p class="users-name"><%= @user_select.name %></p>
			<p class="users-posts-counter">Number of posts: <%= @user_select.posts_counter %></p>
		</div>
	</div>
	<div class="posts-container">
		<% @posts.each do |post| %>
			<div class="post-comments">
				<div class="posts">
					<%= link_to user_post_path(@user_select, post), method: :get do %>
						<p><%= post.title %></p>
					<% end %>
					<div id="posts-title">
						<% if can? :edit, post %>
              <%= link_to edit_user_post_path(id: post.id, user_id: post.author_id), method: :get, class: 'button-posts' do %>
                Edit
                <i class="fa-solid fa-pen-to-square"></i>
              <% end %>
            <% end %>
            <% if can? :destroy, post %>
            	<%= button_to user_post_path(@user_select, post), action: 'destroy', data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, remote: true, class: 'button-posts' do %>
               	<i class="fa-solid fa-trash-can"></i>
               	Delete
              <% end %>
            <% end %>
					</div>
					<p><%= post.text.truncate(50) %></p>
					<p>
						<span>Comments: <%= post.comments_counter %></span>
						<span>Likes: <%= post.likes_counter %>
						</span>
					</p>
				</div>
				<div class="posts-comments">
					<% post.comments.includes(:user).order(updated_at: :desc).limit(5).each do |comment| %>
						<p>
							<strong><%= comment.user.name %>:</strong>
							<span> <%= comment.text %> </span>
						</p>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
	<% unless @posts.empty? %>
		<%= link_to user_post_path(@user_select, @posts[0]), method: :get, class: 'button-posts' do %>
			Pagination
		<% end %>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="users-container">
	<div id="posts-bar">
		<%= link_to :back, method: :get, class: 'button-posts' do %>
				<i class="fas fa-arrow-left"></i> Back to User
			<% end %>
		<h1 style="text-align: center;">New Post</h1>
	</div>
	<%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="posts-container">
	<%= link_to user_posts_path(@user_select), method: :get, class: 'button-posts' do %>
    <i class="fas fa-arrow-left"></i> Back to User
  <% end %>
	<div class="post-comments">
		<div class="post">
			<div class="post-title">
				<div class="post-flex">
					<h3><%= @post.title %> by <%= User.find(@post.author_id).name %> </h3>
					<% if @like %>
						<%= button_to user_post_like_path(@user_select, @post, @like), action: 'destroy', method: :delete, remote: true, class: 'button-like' do %>
						 <i class="fa-solid fa-heart like"></i>
						 <% end %>
					<% else %>
						<%= button_to user_post_likes_path(@user_select, @post), method: :post, class: 'button-like' do %>
						<i class="fa-solid fa-heart not-like"></i>
						<% end %>
					<% end %>
				</div>
				<p>
					<span>Comments: <%= @post.comments_counter %></span>
					<span>Likes: <%= @post.likes_counter %></span>
				</p>
			</div>
			<p>
				<%= @post.text %>
			</p>
		</div>
		<div class="comments">
			<%= render 'comments/form' %>
			<% @comments.each do |comment| %>
				<div class="comment-flex">
					<p>
						<strong><%= comment.user.name %>:</strong>
						<span><%= comment.text %></span>
					</p>
					<% if can? :destroy, comment %>
						<%= button_to user_post_comment_path(@user_select, @post, comment), action: 'destroy', data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, remote: true, class: 'button-delete' do %>
							<i class="fa-solid fa-trash-can"></i>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="buttons-container">
		<% if @previous_post %>
      <%= link_to user_post_path(user_id: @user_select.id, id: @previous_post.id), method: :get, class: 'button-posts' do %>
       Previous Post
      <% end %>
    <% end %>
		<% if @next_post %>
      <%= link_to user_post_path(user_id: @user_select.id, id: @next_post.id), method: :get, class: 'button-posts' do %>
      	Next Post
      <% end %>
    <% end %>
	</div>
</div>